In [29]:
import numpy as np

In [30]:
import pandas as pd

In [31]:
from sklearn.model_selection import train_test_split

In [32]:
from sklearn.preprocessing import StandardScaler

In [33]:
df = pd.read_csv(r"Churn_Modelling.csv")

In [34]:
df.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [35]:
x=df.drop(['Exited','RowNumber','CustomerId','Surname'],axis=1)

In [36]:
x

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary
0,619,France,Female,42,2,0.00,1,1,1,101348.88
1,608,Spain,Female,41,1,83807.86,1,0,1,112542.58
2,502,France,Female,42,8,159660.80,3,1,0,113931.57
3,699,France,Female,39,1,0.00,2,0,0,93826.63
4,850,Spain,Female,43,2,125510.82,1,1,1,79084.10
...,...,...,...,...,...,...,...,...,...,...
9995,771,France,Male,39,5,0.00,2,1,0,96270.64
9996,516,France,Male,35,10,57369.61,1,1,1,101699.77
9997,709,France,Female,36,7,0.00,1,0,1,42085.58
9998,772,Germany,Male,42,3,75075.31,2,1,0,92888.52
9999,792,France,Female,28,4,130142.79,1,1,0,38190.78

In [37]:
y=df['Exited']

In [38]:
y.head()

0    1
1    0
2    1
3    0
4    0
Name: Exited, dtype: int64

In [39]:
from sklearn.preprocessing import LabelEncoder
lb=LabelEncoder()
df['Gender']=lb.fit_transform(df['Gender'])

In [40]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
ct = ColumnTransformer(
    transformers=[('geo', OneHotEncoder(drop='first'), ['Geography'])],
    remainder='passthrough'
)
X_encoded = ct.fit_transform(x)

In [41]:
X_train, X_test, y_train, y_test = train_test_split(
    x, y, test_size=0.2, random_state=42
)

In [43]:
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

ValueError: could not convert string to float: 'France'

In [44]:
import numpy as np
import pandas as pd
import tensorflow as tf
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder, OneHotEncoder
from sklearn.compose import ColumnTransformer

# Load dataset
df = pd.read_csv('Churn_Modelling.csv')

# Drop non-predictive identifier columns (e.g., RowNumber, CustomerId, Surname)
X = df.drop(columns=['RowNumber', 'CustomerId', 'Surname', 'Exited'])
y = df['Exited']  # Target variable (1 = Churn, 0 = Stay)

In [46]:
df.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [45]:
# 1. Encode 'Gender' (Binary: Male/Female -> 1/0)
le = LabelEncoder()
X['Gender'] = le.fit_transform(X['Gender'])

In [51]:
le2=LabelEncoder()
X['Geography']=le.fit_transform(X['Geography'])

In [52]:
#Train-Test Split (80% train, 20% test)
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

In [53]:
X.head()

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,\tGeography
0,619,0,0,42,2,0.00,1,1,1,101348.88,0
1,608,2,0,41,1,83807.86,1,0,1,112542.58,2
2,502,0,0,42,8,159660.80,3,1,0,113931.57,0
3,699,0,0,39,1,0.00,2,0,0,93826.63,0
4,850,2,0,43,2,125510.82,1,1,1,79084.10,2

In [54]:
# 4. Feature Scaling (essential for gradient descent convergence)
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [55]:
#Building an ANN model
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [60]:
model=Sequential()
model.add(Dense(16,activation='relu',input_shape=(11,)))
model.add(Dense(8,activation='relu'))
model.add(Dense(1,activation='sigmoid'))

c:\Users\user\anaconda3\Lib\site-packages\keras\src\layers\core\dense.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [61]:
#COmpilemodel
model.compile(optimizer='adam',
              loss='binary_crossentropy',
              metrics=["accuracy"])

In [62]:
history=model.fit(X_train,y_train,epochs=50,batch_size=32,validation_split=0.2)

Epoch 1/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.7823 - loss: 0.4992 - val_accuracy: 0.7987 - val_loss: 0.4491
Epoch 2/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.7983 - loss: 0.4322 - val_accuracy: 0.8031 - val_loss: 0.4247
Epoch 3/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8139 - loss: 0.4114 - val_accuracy: 0.8319 - val_loss: 0.4086
Epoch 4/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8317 - loss: 0.3971 - val_accuracy: 0.8419 - val_loss: 0.3954
Epoch 5/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8380 - loss: 0.3862 - val_accuracy: 0.8494 - val_loss: 0.3816
Epoch 6/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8428 - loss: 0.3774 - val_accuracy: 0.8569 - val_loss: 0.3718
Epoch 7/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8478 - loss: 0.3701 - val_accuracy: 0.8556 - val_loss: 0.3661
Epoch 8/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8497 - loss: 0.3647 - val_accuracy: 0.8594 - val_loss: 0.3582
Epoch 9/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - accuracy: 0.8525 - loss: 0.3606 - val_accuracy: 0.8612 - val_loss: 0.3543
Epoch 10/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - accuracy: 0.8530 - loss: 0.3576 - val_accuracy: 0.8600 - val_loss: 0.3520
Epoch 11/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - accuracy: 0.8547 - loss: 0.3553 - val_accuracy: 0.8606 - val_loss: 0.3488
Epoch 12/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - accuracy: 0.8559 - loss: 0.3530 - val_accuracy: 0.8606 - val_loss: 0.3470
Epoch 13/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - accuracy: 0.8553 - loss: 0.3511 - val_accuracy: 0.8631 - val_loss: 0.3465
Epoch 14/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - accuracy: 0.8553 - loss: 0.3491 - val_accuracy: 0.8619 - val_loss: 0.3445
Epoch 15/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - accuracy: 0.8570 - loss: 0.3475 - val_accuracy: 0.8637 - val_loss: 0.3431
Epoch 16/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - accuracy: 0.8567 - loss: 0.3468 - val_accuracy: 0.8656 - val_loss: 0.3436
Epoch 17/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - accuracy: 0.8564 - loss: 0.3458 - val_accuracy: 0.8669 - val_loss: 0.3430
Epoch 18/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - accuracy: 0.8562 - loss: 0.3440 - val_accuracy: 0.8662 - val_loss: 0.3406
Epoch 19/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - accuracy: 0.8570 - loss: 0.3435 - val_accuracy: 0.8662 - val_loss: 0.3413
Epoch 20/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - accuracy: 0.8591 - loss: 0.3422 - val_accuracy: 0.8675 - val_loss: 0.3400
Epoch 21/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8581 - loss: 0.3410 - val_accuracy: 0.8656 - val_loss: 0.3395
Epoch 22/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8581 - loss: 0.3403 - val_accuracy: 0.8675 - val_loss: 0.3410
Epoch 23/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8608 - loss: 0.3396 - val_accuracy: 0.8656 - val_loss: 0.3399
Epoch 24/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8555 - loss: 0.3393 - val_accuracy: 0.8669 - val_loss: 0.3386
Epoch 25/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8573 - loss: 0.3386 - val_accuracy: 0.8662 - val_loss: 0.3382
Epoch 26/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8592 - loss: 0.3373 - val_accuracy: 0.8650 - val_loss: 0.3367
Epoch 27/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8570 - loss: 0.3373 - val_accuracy: 0.8644 - val_loss: 0.3417
Epoch 28/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8580 - loss: 0.3365 - val_accuracy: 0.8644 - val_loss: 0.3360
Epoch 29/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8587 - loss: 0.3359 - val_accuracy: 0.8650 - val_loss: 0.3360
Epoch 30/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8605 - loss: 0.3350 - val_accuracy: 0.8669 - val_loss: 0.3357
Epoch 31/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8591 - loss: 0.3336 - val_accuracy: 0.8644 - val_loss: 0.3370
Epoch 32/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8602 - loss: 0.3331 - val_accuracy: 0.8625 - val_loss: 0.3370
Epoch 33/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8600 - loss: 0.3329 - val_accuracy: 0.8662 - val_loss: 0.3364
Epoch 34/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8600 - loss: 0.3320 - val_accuracy: 0.8675 - val_loss: 0.3397
Epoch 35/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8616 - loss: 0.3314 - val_accuracy: 0.8637 - val_loss: 0.3367
Epoch 36/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8602 - loss: 0.3320 - val_accuracy: 0.8656 - val_loss: 0.3362
Epoch 37/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8620 - loss: 0.3311 - val_accuracy: 0.8644 - val_loss: 0.3368
Epoch 38/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8616 - loss: 0.3305 - val_accuracy: 0.8619 - val_loss: 0.3382
Epoch 39/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8608 - loss: 0.3300 - val_accuracy: 0.8669 - val_loss: 0.3371
Epoch 40/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8620 - loss: 0.3300 - val_accuracy: 0.8644 - val_loss: 0.3359
Epoch 41/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8609 - loss: 0.3297 - val_accuracy: 0.8619 - val_loss: 0.3373
Epoch 42/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8630 - loss: 0.3285 - val_accuracy: 0.8600 - val_loss: 0.3380
Epoch 43/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8606 - loss: 0.3293 - val_accuracy: 0.8637 - val_loss: 0.3363
Epoch 44/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8616 - loss: 0.3285 - val_accuracy: 0.8631 - val_loss: 0.3374
Epoch 45/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8611 - loss: 0.3282 - val_accuracy: 0.8644 - val_loss: 0.3377
Epoch 46/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8617 - loss: 0.3279 - val_accuracy: 0.8644 - val_loss: 0.3386
Epoch 47/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8612 - loss: 0.3271 - val_accuracy: 0.8675 - val_loss: 0.3375
Epoch 48/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8605 - loss: 0.3268 - val_accuracy: 0.8644 - val_loss: 0.3374
Epoch 49/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8625 - loss: 0.3265 - val_accuracy: 0.8650 - val_loss: 0.3383
Epoch 50/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8627 - loss: 0.3262 - val_accuracy: 0.8656 - val_loss: 0.3381

In [63]:
loss, accuracy = model.evaluate(X_test, y_test)

print("Test Accuracy:", accuracy)

63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8530 - loss: 0.3515
Test Accuracy: 0.8529999852180481

In [69]:
from sklearn.metrics import confusion_matrix, classification_report

In [ ]:
predictions = model.predict(X_test)
predictions = (predictions >= 0.5)

print(predictions[:10])

63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
[[False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [ True]
 [False]]

In [71]:
cm=confusion_matrix(y_test,predictions)

In [72]:
cm

array([[1537,   56],
       [ 238,  169]])

In [74]:
print(classification_report(y_test,predictions))

              precision    recall  f1-score   support

           0       0.87      0.96      0.91      1593
           1       0.75      0.42      0.53       407

    accuracy                           0.85      2000
   macro avg       0.81      0.69      0.72      2000
weighted avg       0.84      0.85      0.84      2000

In [ ]:
predictions = (predictions > 0.5).astype(int)

print(predictions[:10])

[[0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [0]]

In [ ]:
model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_3 (Dense)                 │ (None, 16)             │           192 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_4 (Dense)                 │ (None, 8)              │           136 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_5 (Dense)                 │ (None, 1)              │             9 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 1,013 (3.96 KB)

 Trainable params: 337 (1.32 KB)

 Non-trainable params: 0 (0.00 B)

 Optimizer params: 676 (2.64 KB)

In [ ]:
print("Predicted:", predictions[:10])
print("Actual:", y_test[:10])

Predicted: [[0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [0]]
Actual: 5702    0
3667    0
1617    0
5673    0
4272    0
8270    0
7079    0
5295    0
845     0
5311    0
Name: Exited, dtype: int64

In [75]:
# Pass class_weight into fit()
history = model.fit(
    X_train, y_train,
    epochs=50,
    batch_size=32,
    validation_split=0.2,
    class_weight={0: 1.0, 1: 3.9}  # Weight ratio based on ~1593/407 ratio
)

Epoch 1/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.7937 - loss: 0.7292 - val_accuracy: 0.7925 - val_loss: 0.4317
Epoch 2/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7983 - loss: 0.7099 - val_accuracy: 0.7944 - val_loss: 0.4254
Epoch 3/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7961 - loss: 0.7045 - val_accuracy: 0.7906 - val_loss: 0.4433
Epoch 4/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7948 - loss: 0.7049 - val_accuracy: 0.7869 - val_loss: 0.4490
Epoch 5/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7980 - loss: 0.7002 - val_accuracy: 0.7862 - val_loss: 0.4408
Epoch 6/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7936 - loss: 0.6997 - val_accuracy: 0.7875 - val_loss: 0.4353
Epoch 7/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7987 - loss: 0.6974 - val_accuracy: 0.7794 - val_loss: 0.4468
Epoch 8/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7987 - loss: 0.6976 - val_accuracy: 0.7731 - val_loss: 0.4602
Epoch 9/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7941 - loss: 0.6965 - val_accuracy: 0.7981 - val_loss: 0.4278
Epoch 10/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7995 - loss: 0.6951 - val_accuracy: 0.7887 - val_loss: 0.4345
Epoch 11/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7972 - loss: 0.6944 - val_accuracy: 0.7800 - val_loss: 0.4437
Epoch 12/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7964 - loss: 0.6937 - val_accuracy: 0.7831 - val_loss: 0.4482
Epoch 13/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.7975 - loss: 0.6921 - val_accuracy: 0.7763 - val_loss: 0.4515
Epoch 14/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.7959 - loss: 0.6912 - val_accuracy: 0.7837 - val_loss: 0.4363
Epoch 15/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8002 - loss: 0.6913 - val_accuracy: 0.7900 - val_loss: 0.4311
Epoch 16/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.7995 - loss: 0.6895 - val_accuracy: 0.7837 - val_loss: 0.4405
Epoch 17/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.7991 - loss: 0.6900 - val_accuracy: 0.7806 - val_loss: 0.4429
Epoch 18/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8011 - loss: 0.6889 - val_accuracy: 0.7812 - val_loss: 0.4439
Epoch 19/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.7983 - loss: 0.6902 - val_accuracy: 0.7962 - val_loss: 0.4219
Epoch 20/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8033 - loss: 0.6868 - val_accuracy: 0.7681 - val_loss: 0.4694
Epoch 21/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8022 - loss: 0.6878 - val_accuracy: 0.7781 - val_loss: 0.4473
Epoch 22/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7984 - loss: 0.6877 - val_accuracy: 0.7956 - val_loss: 0.4265
Epoch 23/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8012 - loss: 0.6852 - val_accuracy: 0.7675 - val_loss: 0.4587
Epoch 24/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7994 - loss: 0.6870 - val_accuracy: 0.7931 - val_loss: 0.4295
Epoch 25/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8014 - loss: 0.6846 - val_accuracy: 0.7894 - val_loss: 0.4282
Epoch 26/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8020 - loss: 0.6840 - val_accuracy: 0.7706 - val_loss: 0.4572
Epoch 27/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8003 - loss: 0.6834 - val_accuracy: 0.7906 - val_loss: 0.4336
Epoch 28/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8011 - loss: 0.6827 - val_accuracy: 0.7825 - val_loss: 0.4486
Epoch 29/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8027 - loss: 0.6827 - val_accuracy: 0.7800 - val_loss: 0.4500
Epoch 30/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7998 - loss: 0.6826 - val_accuracy: 0.7825 - val_loss: 0.4480
Epoch 31/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8034 - loss: 0.6812 - val_accuracy: 0.7850 - val_loss: 0.4338
Epoch 32/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8033 - loss: 0.6806 - val_accuracy: 0.7875 - val_loss: 0.4405
Epoch 33/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8003 - loss: 0.6821 - val_accuracy: 0.7937 - val_loss: 0.4299
Epoch 34/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8073 - loss: 0.6807 - val_accuracy: 0.7688 - val_loss: 0.4676
Epoch 35/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8006 - loss: 0.6810 - val_accuracy: 0.7794 - val_loss: 0.4489
Epoch 36/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7956 - loss: 0.6800 - val_accuracy: 0.7925 - val_loss: 0.4408
Epoch 37/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8023 - loss: 0.6791 - val_accuracy: 0.7962 - val_loss: 0.4384
Epoch 38/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8016 - loss: 0.6786 - val_accuracy: 0.7900 - val_loss: 0.4450
Epoch 39/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8050 - loss: 0.6778 - val_accuracy: 0.7700 - val_loss: 0.4721
Epoch 40/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8005 - loss: 0.6780 - val_accuracy: 0.8000 - val_loss: 0.4335
Epoch 41/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8028 - loss: 0.6770 - val_accuracy: 0.7894 - val_loss: 0.4459
Epoch 42/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8044 - loss: 0.6745 - val_accuracy: 0.7781 - val_loss: 0.4540
Epoch 43/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8000 - loss: 0.6783 - val_accuracy: 0.7906 - val_loss: 0.4428
Epoch 44/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8028 - loss: 0.6755 - val_accuracy: 0.7850 - val_loss: 0.4466
Epoch 45/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8009 - loss: 0.6747 - val_accuracy: 0.7919 - val_loss: 0.4361
Epoch 46/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8050 - loss: 0.6753 - val_accuracy: 0.7812 - val_loss: 0.4478
Epoch 47/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8058 - loss: 0.6744 - val_accuracy: 0.7700 - val_loss: 0.4695
Epoch 48/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8011 - loss: 0.6730 - val_accuracy: 0.7981 - val_loss: 0.4215
Epoch 49/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8067 - loss: 0.6748 - val_accuracy: 0.7788 - val_loss: 0.4459
Epoch 50/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8028 - loss: 0.6728 - val_accuracy: 0.7825 - val_loss: 0.4487

In [76]:
loss, accuracy = model.evaluate(X_test, y_test)

print("Test Accuracy:", accuracy)

63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7805 - loss: 0.4623
Test Accuracy: 0.7804999947547913

In [77]:
cm=confusion_matrix(y_test,predictions)

In [78]:
cm

array([[1537,   56],
       [ 238,  169]])

In [79]:
print(classification_report(y_test,predictions))

              precision    recall  f1-score   support

           0       0.87      0.96      0.91      1593
           1       0.75      0.42      0.53       407

    accuracy                           0.85      2000
   macro avg       0.81      0.69      0.72      2000
weighted avg       0.84      0.85      0.84      2000

In [80]:
# 1. Evaluate on test set (Returns Loss & Accuracy)
test_loss, test_acc = model.evaluate(X_test, y_test)
print(f"Test Accuracy from evaluate(): {test_acc:.4f}")

# 2. Generate predictions on the SAME test set
y_pred_probs = model.predict(X_test)
y_pred = (y_pred_probs > 0.5).astype(int)

# 3. Print classification report
from sklearn.metrics import classification_report
print("\nClassification Report:")
print(classification_report(y_test, y_pred))

63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7805 - loss: 0.4623
Test Accuracy from evaluate(): 0.7805
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step

Classification Report:
              precision    recall  f1-score   support

           0       0.92      0.79      0.85      1593
           1       0.47      0.75      0.58       407

    accuracy                           0.78      2000
   macro avg       0.70      0.77      0.72      2000
weighted avg       0.83      0.78      0.80      2000

In [81]:
import joblib

# 1. Save the Keras ANN model (.h5 or .keras format)
model.save('churn_ann_model.keras')

# 2. Save the fitted StandardScaler
joblib.dump(sc, 'scaler.joblib')

# 3. Save the OneHotEncoder / ColumnTransformer (if applicable)
joblib.dump(ct, 'column_transformer.joblib')

['column_transformer.joblib']